# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3cef4db73bea929bc465f088b050b3faa874e4320095895ee7d855d62d2a3c009135d00c5c54d8737d501beb13b80fb4154dafada31eaac53b9ec171fb2436f

test:
  secret_key_base: 6d3f5aa5500337d272aeb51e6cf38c89f2c0321188e09b47ca7e109b0d4435daca862da6b331e6bb542bda4f73a0ee1881a7401d3034df381e215055adc96461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
